name: CI

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build

      - name: Copy robots.txt to build output
        run: cp robots.txt dist/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.SHANXIKUG }}
          publish_dir: ./dist
          publish_branch: gh-pages
